### GET EQP List
GET http://localhost:8080/lvs/get/eqpList
Accept: application/json

### GET EQP detail
GET http://localhost:8080/lvs/get/scenario/AP-RD-04-01
Accept: application/json




### GET All Logs
GET http://localhost:8080/lvs/get/allLogs
Accept: application/json

### GET Detail Log
GET http://localhost:8080/lvs/get/logs/1717447410030-cdebe024-2a60-4534-b12c-32c09b224792
Accept: application/json

### POST Request File read
POST http://localhost:8080/lvs/file/read
Content-Type: application/json

{
"path": "C:\\Users\\DavidKim\\OneDrive - Absolics Inc\\Documents\\Documentation\\운영\\테스트\\설비연동테스트_202401\\AT-05-01\\2차_20240215",
"name": "bwappnode.log"
}
